name: FreeRDP

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-latest

    timeout-minutes: 9999

    steps:

    - name: Mendownload Ngrok.

      run: |

        Invoke-WebRequest https://raw.githubusercontent.com/iamyahweh/RDP_76-main/main/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

        Invoke-WebRequest https://github.com/iamyahweh/RDP_76-main/blob/main/start.bat -OutFile start.bat

        Invoke-WebRequest https://github.com/iamyahweh/RDP_76-main/blob/main/wallpaper.jpg -OutFile wallpaper.jpg

        Invoke-WebRequest https://github.com/iamyahweh/RDP_76-main/blob/main/wallpaper.bat -OutFile wallpaper.bat

        Invoke-WebRequest https://github.com/iamyahweh/RDP_76-main/blob/main/loop.ps1 -OutFile loop.ps1

    - name: Mendownload Launcher.

      run: |

        Invoke-WebRequest https://raw.githubusercontent.com/EmanSaputra/FreeRDP/main/launcher/Node.js.lnk -OutFile Node.js.lnk

        Invoke-WebRequest https://raw.githubusercontent.com/EmanSaputra/FreeRDP/main/launcher/Visual%20Studio%202019.lnk -OutFile "Visual Studio 2019.lnk"

        Invoke-WebRequest https://github.com/EmanSaputra/FreeRDP/raw/main/launcher/Ganti%20Password.exe -OutFile "Ganti Password.exe"

    - name: Mengextract Ngrok File.

      run: Expand-Archive ngrok.zip

    - name: Connect Ke Akun Ngrok.

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Mengaktifkan Akses RDP.

      run: | 

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

        copy wallpaper.bmp D:\a\wallpaper.bmp

        copy wallpaper.bat D:\a\wallpaper.bat

        copy Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk

        copy "Visual Studio 2019.lnk" "C:\Users\Public\Desktop\Visual Studio 2019.lnk"

        copy "Ganti Password.exe" "C:\Users\Public\Desktop\Ganti Password.exe"

    - name: Membuat Tunnel.

      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'

    - name: Connect Ke RDP Kamu CPU 2 Core - 7GB Ram - 500 SSD.

      run: cmd /c start.bat

    - name: Berhasil Dibuat! Anda Bisa Menutup Tab Sekarang.

      run: cmd /c loop.bat
